### ISSUE TITLE
因为该项目，导致一些垃圾人知道盘搜网站，从而以极高频率爬取资源

### ISSUE THREAD

**Issue by Xwudao** [unilei/aipan-netdisk-search#10]
导致了很多网站目前运行缓慢，并不能向正常用户提供服务。

请立即删除没有明确提供开放接口的源【网站】

并且 [ReMan](https://docs.hunhepan.com/reman/) 后面会将接口进行混淆。

附爬虫信息：

![image](https://github.com/unilei/aipan-netdisk-search/assets/31327868/117f4ea0-07d2-47e9-b808-d6057a589559)

IP归属地：中国江苏省徐州市铜山区

[https://ip138.com/iplookup.php?ip=112.2.164.100&action=2](https://ip138.com/iplookup.php?ip=112.2.164.100&action=2)

**Comment by unilei** [comment]
> 导致了很多网站目前运行缓慢，并不能向正常用户提供服务。
> 
> 请立即删除没有明确提供开放接口的源【网站】
> 
> 并且 [ReMan](https://docs.hunhepan.com/reman/) 后面会将接口进行混淆。
> 
> 附爬虫信息：
> 
> ![image](https://private-user-images.githubusercontent.com/31327868/332418942-117f4ea0-07d2-47e9-b808-d6057a589559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTUyNzcsIm5iZiI6MTcxNjI5NDk3NywicGF0aCI6Ii8zMTMyNzg2OC8zMzI0MTg5NDItMTE3ZjRlYTAtMDdkMi00N2U5LWI4MDgtZDYwNTdhNTg5NTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEyMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMDA0YTE5NzE4NjAyMDExNTg3ZTM4ODhmY2ZmZDViNWExNzMzZTJmMGMzZGZjMjMwNGExNjA0MTM0YjEyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9eEZS7G4uNSzVXYzfBOdypZcDDPKoSbfXKGOTxSu5-M)
> 
> IP归属地：中国江苏省徐州市铜山区
> 
> https://ip138.com/iplookup.php?ip=112.2.164.100&action=2

好吧，sorry，没想到这么严重，源已删。

**Comment by unilei** [comment]
所以你的这个混合盘的api，到底能不能用呢？

**Comment by Xwudao** [comment]
> 请立即删除没有明确提供开放接口的源【网站】

理论上可以；

实际上，你要是使用其它网站的接口，我也不会多管闲事（ https://www.pansou.vip/ ）

**Comment by unilei** [comment]
> > 请立即删除没有明确提供开放接口的源【网站】
> 
> 理论上可以；
> 
> 实际上，你要是使用其它网站的接口（非ReMan系），我也不会多管闲事（ https://www.pansou.vip/ ）

那我保留混合盘api啦，无聊写着玩的，本意是想聚合在一起用，用起来比较方便。没想到坏人辣么多。
