### ISSUE TITLE
可以往里面添加自己资源站的接口么？

### ISSUE THREAD

**Issue by a52948** [unilei/aipan-netdisk-search#16]
是不是只需要改search-multi.ts这个文件就可以？

**Comment by a52948** [comment]
有很多影视资源站，他们已提供了api接口，想自己找一些，添加进去

**Comment by unilei** [comment]
> 有很多影视资源站，他们已提供了api接口，想自己找一些，添加进去

可以加，去api目录下先重新封装下影视站的api
