### ISSUE TITLE
关于反代问题

### ISSUE THREAD

**Issue by alleninfo** [unilei/aipan-netdisk-search#17]
你好，我用nginx反代，开启https，然后无法显示搜索框，以及logo，请问是哪里错误？日志也没报错。。

location / {
        proxy_pass http://localhost:3000;  # 将请求转发到本地的 8080 端口
        proxy_set_header Host $host;       # 转发请求时保留原始的 Host 头
        proxy_set_header X-Real-IP $remote_addr;  # 转发客户端的 IP 地址
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # 转发客户端的 IP 地址链
        proxy_set_header REMOTE-HOST $remote_addr;

![QQ_1724208304636](https://github.com/user-attachments/assets/17866254-dc3a-4157-8485-2da15b65ad25)

**Comment by unilei** [comment]
> 你好，我用nginx反代，开启https，然后无法显示搜索框，以及logo，请问是哪里错误？日志也没报错。。
> 
> 
> 
> location / {
> 
>         proxy_pass http://localhost:3000;  # 将请求转发到本地的 8080 端口
> 
>         proxy_set_header Host $host;       # 转发请求时保留原始的 Host 头
> 
>         proxy_set_header X-Real-IP $remote_addr;  # 转发客户端的 IP 地址
> 
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # 转发客户端的 IP 地址链
> 
>         proxy_set_header REMOTE-HOST $remote_addr;
> 
> 
> 
> 
> 
> ![QQ_1724208304636](https://github.com/user-attachments/assets/17866254-dc3a-4157-8485-2da15b65ad25)
> 
> 

我直接用的宝塔😅， 这个有时间我看看😂

**Comment by alleninfo** [comment]
我用的aapanel，不知道是不是面板bug。。。直接用ip加端口的方式访问没问题。
