### ISSUE TITLE
数据库URL问题

### ISSUE THREAD

**Issue by ExoticSkywing** [unilei/aipan-netdisk-search#20]
无论怎么试都是报这个错![image](https://github.com/user-attachments/assets/597f9b38-6cc7-4f13-8931-ec473f3c8913)

**Comment by cooker** [comment]
有mysql配置吗？

**Comment by ExoticSkywing** [comment]
![image](https://github.com/user-attachments/assets/4df142c5-2061-4446-be04-1666da4d578e)
![image](https://github.com/user-attachments/assets/65376bd5-6af0-4d7a-80f6-9041a8213e36)

**Comment by unilei** [comment]
> ![image](https://github.com/user-attachments/assets/4df142c5-2061-4446-be04-1666da4d578e)
> 
> ![image](https://github.com/user-attachments/assets/65376bd5-6af0-4d7a-80f6-9041a8213e36)
> 
> 

![image](https://github.com/user-attachments/assets/77e95576-1a23-4db4-b696-398cc1882720)

![image](https://github.com/user-attachments/assets/8f240c97-6abd-40e2-85e2-737445bff54b)

这两个全都用MySQL的那个文件里的内容

**Comment by ExoticSkywing** [comment]
没懂什么意思

**Comment by unilei** [comment]
> 没懂什么意思

目录:lib里面有两个文件， 你把prisma.mysql.js里面的内容复制到prisma.js里面， 另一个同样

**Comment by ExoticSkywing** [comment]
![image](https://github.com/user-attachments/assets/57bb4b4b-fe10-457c-b206-d5f982395cf6)
还是不行，还是原来的报错

**Comment by unilei** [comment]
这里是dockerfile里面有个变量名字写错了，已经改过来来了，更新下最新代码就好了
