### ISSUE TITLE
用域名访问会导致域名被封？

### ISSUE THREAD

**Issue by nanshancc** [unilei/aipan-netdisk-search#22]

**Comment by unilei** [comment]
> 

你说的是域名被微信屏蔽吧！
只要是不备案的，过不了多久都会被屏蔽。

包括分享网盘资源的网站基本上都不能直接在微信访问，都会被屏蔽的，用浏览器打开能够访问就行了！

**Comment by nanshancc** [comment]
浏览器也被屏蔽了我两个域名都不能解析了

**Comment by unilei** [comment]
额，域名不能解析应该是跟服务商运营商联系，这个程序是不会导致域名被封的，因为这是没什么道理的。我的域名部署的比你的要早的多吧，现在是好的呀，亲在 2024年8月31日，21:20，nanshancc ***@***.***> 写道：﻿
浏览器也被屏蔽了我两个域名都不能解析了
