### ISSUE TITLE
用docker部署爱盼后无法下载音乐

### ISSUE THREAD

**Issue by milesxia** [unilei/aipan-netdisk-search#27]
音乐搜索都没有问题，点击下载后无法复制出音乐下载地址，使用https://www.kkwnhub.com/music进行下载是无问题的
设备为威联通464c nas

**Comment by unilei** [comment]
为什么呢？我没有nas来测试这个

**Comment by milesxia** [comment]
抱歉我也不太懂这个，只是实际docker部署后操作发现的问题，本想问问您是否有什么答案，貌似也没办法了，感谢呀

**Comment by iowong** [comment]
群辉和服务器部署的都不能下载音乐 不确定是不是第三方编译的镜像有问题
![微信截图_20240909200109](https://github.com/user-attachments/assets/19f74c04-83c3-4b8c-8121-b5ef9da8c35f)

**Comment by milesxia** [comment]
> 群辉和服务器部署的都不能下载音乐 不确定是不是第三方编译的镜像有问题 ![微信截图_20240909200109](https://private-user-images.githubusercontent.com/74191259/365641396-19f74c04-83c3-4b8c-8121-b5ef9da8c35f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzY0MDQsIm5iZiI6MTcyNTkzNjEwNCwicGF0aCI6Ii83NDE5MTI1OS8zNjU2NDEzOTYtMTlmNzRjMDQtODNjMy00YjhjLTgxMjEtYjVlZjlkYThjMzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAyNDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMWEzYmMzZDI3MDI3OGIyMTQxOTQxZGQ3OTE4ZTdmYTY0MjUxZjViODRmZjRkYjQ4MmIwODI1MGNkMGNlMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o6dG3pLncPhDTKOavohzfyFt42UhlWCe6Mpvi0KqApU)

我尝试过按照官方说明文件下载数据包后安装，结果是一样的

**Comment by ilcxyz** [comment]
是的，刚刚用docker部署的，也是无法下载音乐，复制不到链接
