### ISSUE TITLE
截止Issues创建前的版本，在Windows下执行本地build命令会出现第三方依赖错误：RollupError: Expected ',', got 'undefined' in /xxx/node_modules/papaparse/papaparse.js

### ISSUE THREAD

**Issue by dosicker** [unilei/aipan-netdisk-search#28]
【环境设备】：
系统：Windows 10 21H2
源码版本：[该issues发帖时最新主干版本](https://github.com/unilei/aipan-netdisk-search/tree/de6f26017d804f95cf0513dccb9ba77ccd95fc9f)
node Version：18.20.4
npm Version：10.7.0

【重现步骤】：
将以上版本代码clone至本地后，先install完，看了下页面，然后修改了部分参数配置（实际上不影响，后面还原了这部分数据后仍然无法正常nuxt build）后想本地build一下来看看，结果出现如下图：
![image](https://github.com/user-attachments/assets/da5c6776-71b5-425e-b72f-09e0aca0d3d7)
![image](https://github.com/user-attachments/assets/ca3ac5b2-0313-4f5c-8e4b-2200847b6f5b)
定位看了下，应该是最新版的csv导入功能所引起的，而根源问题是第三方的[papaparse](https://www.papaparse.com/)库引起，而且这个问题在五月初的时候就有人已经出现过了：

[RollupError when deploying to Cloudflare #1056](https://github.com/mholt/PapaParse/issues/1056)
![image](https://github.com/user-attachments/assets/6575a186-f8d0-4379-ba55-58d0b43d962f)

【给个建议】：
看了个大概，感觉这个玩意好像不是很好一下子定位到问题，lei佬 @unilei 考虑更换其他第三方库实现？
[csv-parse](https://github.com/adaltas/node-csv)
[fast-csv](https://github.com/C2FO/fast-csv)
[node-csvtojson](https://github.com/Keyang/node-csvtojson)

另外，这个仓库接PR吗？要是接的话感觉 package-lock.json 这个文件是不是可以考虑不用一起commit上来？因为很多依赖版本会在你本地使用时正常，但是部分用户在install时用你这一个lock版本的话会出现其他问题的概率貌似更大一点😂~
当然，要是lei佬不接PR的话~~当我没说🤐~~
哈哈~

**Comment by unilei** [comment]
建议很好，已采纳，开发时我也没有考虑那么多 
目前我对这个项目的开发前景还没什么好的想法 
。。。

**Comment by dosicker** [comment]
> 建议很好，已采纳，开发时我也没有考虑那么多 目前我对这个项目的开发前景还没什么好的想法 。。。

hh，感谢~ :)
