### ISSUE TITLE
Api相关议题

### ISSUE THREAD

**Issue by JIGEEE** [unilei/aipan-netdisk-search#29]
本人小白一个，很多地方不懂，昨天在本地搭建了aipan。

介绍中看到项目使用的是第三方api，代码里看到调用了ABCD..这些接口

能否实现一下aipan把这些调用的api集合起来，单独成为一个api使用，类似于one api这种项目（将其他ai大模型的key集合起来，oneapi输出一个key，用这个key就可以根据需求程序自动调用起其他的相应模型）

简单说就是怎么实现可以使用aipan的api接口

这样就可以用其他程序发送网络请求aipan，aipan返回响应。

目前我在本地搭建了fastgpt本地知识库项目，并将其接入了微信。fadtgpt工作流里可以发送http网络请求并接收返回信息并筛选输出，我想把本地搭建的aipan也接入进fastgpt，这样即使没有公网和服务器，我远程私聊家庭电脑上的微信也可以进行资源查询。

目前只能实现用项目里的ABCD...接口分别请求并处理信息，如果直接请求192.168..:3000/***?keyword={变量}，返回的事html页面源码，不太懂这个，折腾了挺久来问问有没有什么好的解决办法能实现这个

**Comment by unilei** [comment]
- https://www.aipan.me/api/sources/aipan-search
- https://www.aipan.me/api/sources/aipan-data-search
- https://www.aipan.me/api/sources/aipan-data-search-2
- https://www.aipan.me/api/sources/aipan-data-search-3
- https://www.aipan.me/api/sources/indexE
- https://www.aipan.me/api/sources/indexI

这是api，请求这几个

**Comment by JIGEEE** [comment]
我搭建在本地电脑上，这些地址请求后都没有找到（404错误），地址我填写的是：http://192.168.31.228:3002/api/sources/aipan-search或者http://localhost3002/api/sources/aipan-search，都请求不到，是不支持本地么？
