### ISSUE TITLE
关于分支的疑惑 master和feat-admin-panel 有什么区别？ 该使用哪一个呢？

### ISSUE THREAD

**Issue by CandyMujForks** [unilei/aipan-netdisk-search#32]
关于分支的疑惑 master和feat-admin-panel 有什么区别？ 该使用哪一个呢？

**Comment by unilei** [comment]
- `feat-admin-panel`是我开发用的，功能不master多了个博客功能，后续也会优先在此分支开发新功能，只是部署有门槛。
- `master` 好部署一些。

**Comment by CandyMujForks** [comment]
> * `feat-admin-panel`是我开发用的，功能比master多了个博客功能，后续也会优先在此分支开发新功能，只是部署有门槛。
> * `master` 好部署一些。

原来如此，感谢解惑，给大佬点赞！
