### ISSUE TITLE
管理员的账号密码是什么

### ISSUE THREAD

**Issue by merlinjun** [unilei/aipan-netdisk-search#34]
我看到有登录界面了，但是没有管理员的账号和密码吗？怎么登录后台添加资源？
还有想知道，好像爱盼这样的只能部署到本地吗？
如果放网上的话，API的资源，有资源被投诉侵权怎么删除指定资源呢？

**Comment by unilei** [comment]
![image](https://github.com/user-attachments/assets/bfc55c89-18b5-42ab-9251-bde67dc525d4)
这里是登陆的账号密码。
可以部署到线上。
api来自第三方。

**Comment by merlinjun** [comment]
那应该上线一个屏蔽某些关键词不能搜索的功能，有资源被投诉可以屏蔽掉投诉资源的关键词

**Comment by merlinjun** [comment]
那应该上线一个屏蔽某些关键词不能搜索的功能，有资源被投诉可以屏蔽掉投诉资源的关键词
