### ISSUE TITLE
部署vercel报错：500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by zkjq** [unilei/aipan-netdisk-search#38]

**Comment by Timchacode** [comment]
![image](https://github.com/user-attachments/assets/893d4bef-3af2-411c-9b56-7eb1b47afa34)

**Comment by rangerzhou** [comment]
> 我也是同样的

按 RADEME 配置一下就行了

**Comment by unilei** [comment]
vercel 我测试的，没有遇到问题哟～
