### ISSUE TITLE
执行 docker build 时报错

### ISSUE THREAD

**Issue by rangerzhou** [unilei/aipan-netdisk-search#46]
![image](https://github.com/user-attachments/assets/04078be2-40fa-4164-9f72-9118451f7844)

已经在 Vercel 部署成功且能打开主页正常显示，然后 fork 项目，在我 fork 的 aipan-netdisk-search 根目录下根据 README 执行 docker build，报错如上图，请问这个问题该如何解决呢？

谢谢

**Comment by rangerzhou** [comment]
> 已更新文档，使用docker compose吧，更简单，在项目根目录下创建.env文件，然后执行docker compose up --build -d

好的今晚回去试试

**Comment by rangerzhou** [comment]
SHADOW_DATABASE_URL怎么填写呢，还有 DATABASE_URL 是 postgresql 还是和 Vercel 里一样开头是 postgres 呢？谢谢

**Comment by unilei** [comment]
> SHADOW_DATABASE_URL怎么填写呢，还有 DATABASE_URL 是 postgresql 还是和 Vercel 里一样开头是 postgres 呢？谢谢

这就看你的DATABASE_URL是什么开头的

**Comment by rangerzhou** [comment]
> 已更新文档，使用docker compose吧，更简单，在项目根目录下创建.env文件，然后执行docker compose up --build -d



![image](https://github.com/user-attachments/assets/f8b8ec11-220b-4fb5-9708-ece70613326e)

试了半天，还是不行，我怀疑是不是被墙了，但是我的梯子可以正常使用啊

**Comment by rangerzhou** [comment]
已添加 docker 镜像源解决
