### ISSUE TITLE
Vercel部署，报错看这里。{"code":500,"msg":"error"}

### ISSUE THREAD

**Issue by sunu11** [unilei/aipan-netdisk-search#5]
Vercel 上手动部署后，使用接口返回500， 是需要自己申请第三方接口？

**Comment by unilei** [comment]
![image](https://github.com/unilei/aipan-netdisk-search/assets/29141012/b9b59da1-b5f3-4e00-922d-73199b0f15f6)

地区改成香港试试

**Comment by unilei** [comment]
别忘了重新部署一遍

**Comment by sunu11** [comment]
您好  您的邮件已收到。稍后给您回复。

**Comment by sunu11** [comment]
感谢老哥：
<img width="752" alt="image" src="https://github.com/unilei/aipan-netdisk-search/assets/23350775/9666cc4c-69f0-47c9-8591-3efa0e0f020b">
牛皮

**Comment by sunu11** [comment]
Resolved
