### ISSUE TITLE
docker部署问题

### ISSUE THREAD

**Issue by LIHAQ** [unilei/aipan-netdisk-search#54]
大佬，在自己服务器中使用docker-compose部署数据库和服务，有没有详细的教程，尤其是.env文件中填写的部分，数据库那里如果是自己部署docker的话，不太清楚怎么填写。

**Comment by rangerzhou** [comment]
全都按照 vercel 上 environment 里配置的写

**Comment by LIHAQ** [comment]
安装报这个错误，能麻烦看看嘛
![image](https://github.com/user-attachments/assets/d7d56b6d-79b9-43ee-a43c-9ea717e05eb4)

![image](https://github.com/user-attachments/assets/1a4d22da-bf9f-4333-bae2-b23a1db04866)
