### ISSUE TITLE
关于部署Docker的几个问题

### ISSUE THREAD

**Issue by NJYZ-96** [unilei/aipan-netdisk-search#58]
首先膜拜大佬，项目很好用。

个人有几个问题：
1.官方docker-compose.yml文档中的unilei/aipan-netdisk-search:latest镜像在Docker Hub找不到，删除了？

能否提供一个编译好的镜像呢，自行编译很多人做不到，网友分享的fooololo/aipan-netdisk-search:latest这个镜像很老了，五个月前的，功能缺失

2.涉及版权资源，建议内置一个账号验证功能，方便开放公网给朋友，避免法律风险

3.文档还是有些简单了，环境变量里有数据库的配置，但不设置似乎也能用？不太明白

**Comment by unilei** [comment]
https://github.com/unilei/aipan-netdisk-search/issues/64#issuecomment-2466749042 

docker镜像已更新，请各位打开上面这个查看
