### ISSUE TITLE
docker 部署的和官方示范站，有差异

### ISSUE THREAD

**Issue by star2k** [unilei/aipan-netdisk-search#62]
![image](https://github.com/user-attachments/assets/d0dbe2e5-08c4-4126-bd52-926f82e44527)
![image](https://github.com/user-attachments/assets/5f666e24-cd48-4c27-b941-c5901801e0a5)
官方的功能丰富，自行部署的，功能缺失，是这样，还是哪里没有设置好？

 另外代码中的这个源怎么搜索不到了？
![image](https://github.com/user-attachments/assets/e885bbb5-ab1d-41ef-bb5f-a61ce5d69449)

**Comment by unilei** [comment]
https://github.com/unilei/aipan-netdisk-search/issues/64#issuecomment-2466749042

麻烦您参考这里，我刚打包的新的镜像

这里解释下为什么不一样：
- 看下文档，里面写了feat-add-admin-panel是开发中，代码是最新的，我部署是用的这个分支
- 你部署的时候，我没有把feat-add-admin-panel分支合并到master分支，如果您想用最新的，可以切换到feat分支
