### ISSUE TITLE
神一样的文档，自相矛盾

### ISSUE THREAD

**Issue by 3377** [unilei/aipan-netdisk-search#63]
虽然说用你的，还在吐槽你，但还是不吐不快。要不就不写，要写就写的让人看的明白好吧。
1、第一步，之前已经部署过本项目
那既然已经部署过，还需要部署下面的干嘛？
2、第7步，如果是vercel部署，SHADOW_DATABASE_URL这个为空或不写
正在看的就是vercel部署的教程，忙活了6步，然后让我们不用写，那前面6步是干嘛的？一键部署并没有自动创建数据库。
3、最终到底该怎么用vercel部署，云里雾里。
点击一键部署最终是500错误。

**Comment by unilei** [comment]
角度不同吧，在我看来，部署方式太简单，都没必要写文档

**Comment by 3377** [comment]
很难得你没有生气。
那我为后面的朋友归纳下，其实就两句话
1、新部署，点击一键部署，然后不用管，去setting里面设置相关环境变量，数据库为之前6步获取到的URL
2、部署过，想更换分支，见方法2.
你是说的越多，人家反而不明白了。
