### ISSUE TITLE
docker compose 部署成功，但是实际没成功，首页不对呀

### ISSUE THREAD

**Issue by sundys** [unilei/aipan-netdisk-search#7]
编译整个过程也全部正常，甲骨文的arm主机，ubuntu22.04, 访问主页是Nuxt的默认欢迎页。

![2024-05-20_174013](https://github.com/unilei/aipan-netdisk-search/assets/3960445/1a7957a2-5496-44ba-969a-cdf6658efbfc)

**Comment by ericsource** [comment]
我好遇到了

**Comment by unilei** [comment]
会Docker的朋友，帮忙看下。 但是我在本地机器测试的，是ok的呢

**Comment by alterem** [comment]
> 会Docker的朋友，帮忙看下。 但是我在本地机器测试的，是ok的呢

本想重新修复一下，但是看到了新的提交，我已经决定放弃了

**Comment by alterem** [comment]
尝试一下拉取最新代码后重新部署:'docker compose build && docker compose up -d';
如果还是不行，试试我打包好的镜像吧:' docker run -p 3000:3000 alterem/aipan-netdisk-search:latest '

**Comment by sundys** [comment]
> arm64 尝试一下拉取最新代码后重新部署:'docker compose build && docker compose up -d'; 如果还是不行，试试我打包好的镜像吧:' docker run -p 3000:3000 alterem/aipan-netdisk-search:latest '

谢谢！最新镜像可以部署成功，但是搜索时{"code":500,"msg":"error"}，不知道是不是新加坡主机ip的缘故，看vercel部署要改到香港地区。

**Comment by alterem** [comment]
> > arm64 尝试一下拉取最新代码后重新部署:'docker compose build && docker compose up -d'; 如果还是不行，试试我打包好的镜像吧:' docker run -p 3000:3000 alterem/aipan-netdisk-search:latest '
> 
> 谢谢！最新镜像可以部署成功，但是搜索时{"code":500,"msg":"error"}，不知道是不是新加坡主机ip的缘故，看vercel部署要改到香港地区。

貌似只有全盘会报错，别的都不会

**Comment by sundys** [comment]
> arm64 尝试一下拉取最新代码后重新部署:'docker compose build && docker compose up -d'; 如果还是不行，试试我打包好的镜像吧:' docker run -p 3000:3000 alterem/aipan-netdisk-search:latest '

#4 [aipan-netdisk-search 1/6] FROM docker.io/library/node:alpine@sha256:181d0e0248e825fa1c056c7ef85e91fbad340caf0814d30b81467daea4637045
#4 DONE 0.0s

#5 [aipan-netdisk-search internal] load build context
#5 transferring context: 3.15MB 0.0s done
#5 DONE 0.1s

#6 [aipan-netdisk-search 2/6] WORKDIR /app
#6 CACHED

#7 [aipan-netdisk-search 3/6] COPY . .
#7 DONE 0.1s

#8 [aipan-netdisk-search 4/6] RUN npm install
#8 21.17 
#8 21.17 > nuxt-app@1.0.0 postinstall
#8 21.17 > nuxt prepare
#8 21.17 
#8 21.50 
#8 21.50  ERROR  (node:35) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
#8 21.50 (Use node --trace-deprecation ... to show where the warning was created)
#8 21.50 
#8 24.72 [nuxt:tailwindcss] ℹ Using default Tailwind CSS file
#8 25.38 
#8 25.38  ERROR  (node:35) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
#8 25.38 
#8 26.06 ✔ Types generated in .nuxt
#8 26.17 
#8 26.17 added 1156 packages, and audited 1158 packages in 26s
#8 26.17 
#8 26.17 206 packages are looking for funding
#8 26.17   run `npm fund` for details
#8 26.18 
#8 26.18 found 0 vulnerabilities
#8 26.18 npm notice
#8 26.18 npm notice New minor version of npm available! 10.7.0 -> 10.8.0
#8 26.18 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.0
#8 26.18 npm notice To update run: npm install -g npm@10.8.0
#8 26.18 npm notice
#8 DONE 36.3s

#9 [aipan-netdisk-search 5/6] RUN npm run build
#9 0.416 
#9 0.416 > nuxt-app@1.0.0 build
#9 0.416 > nuxt build
#9 0.416 
#9 0.771 Nuxt 3.11.2 with Nitro 2.9.6
#9 0.783 
#9 0.783  ERROR  (node:17) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
#9 0.783 (Use node --trace-deprecation ... to show where the warning was created)
#9 0.783 
#9 3.696 [nuxt:tailwindcss] ℹ Using default Tailwind CSS file
#9 4.318 
#9 4.318  ERROR  (node:17) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
#9 4.318 
#9 6.085 ℹ Building client...
#9 6.099 ℹ vite v5.2.11 building for production...
#9 6.152 ℹ transforming...
#9 6.877 
#9 6.877  ERROR  (node:17) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
#9 6.877 
#9 6.878 
#9 6.878  ERROR  (node:17) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
#9 6.878 
#9 17.34 ℹ ✓ 1631 modules transformed.



大佬，看下过程有几个地方编译报错，全盘搜索错误，其它正常。

**Comment by alterem** [comment]
> > arm64 尝试一下拉取最新代码后重新部署:'docker compose build && docker compose up -d'; 如果还是不行，试试我打包好的镜像吧:' docker run -p 3000:3000 alterem/aipan-netdisk-search:latest '
> 
> #4 [aipan-netdisk-search 1/6] FROM docker.io/library/node:alpine@sha256:181d0e0248e825fa1c056c7ef85e91fbad340caf0814d30b81467daea4637045 #4 DONE 0.0s
> 
> #5 [aipan-netdisk-search internal] load build context #5 transferring context: 3.15MB 0.0s done #5 DONE 0.1s
> 
> #6 [aipan-netdisk-search 2/6] WORKDIR /app #6 CACHED
> 
> #7 [aipan-netdisk-search 3/6] COPY . . #7 DONE 0.1s
> 
> #8 [aipan-netdisk-search 4/6] RUN npm install #8 21.17 #8 21.17 > nuxt-app@1.0.0 postinstall #8 21.17 > nuxt prepare #8 21.17 #8 21.50 #8 21.50 ERROR (node:35) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated. #8 21.50 (Use node --trace-deprecation ... to show where the warning was created) #8 21.50 #8 24.72 [nuxt:tailwindcss] ℹ Using default Tailwind CSS file #8 25.38 #8 25.38 ERROR (node:35) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension. #8 25.38 #8 26.06 ✔ Types generated in .nuxt #8 26.17 #8 26.17 added 1156 packages, and audited 1158 packages in 26s #8 26.17 #8 26.17 206 packages are looking for funding #8 26.17 run `npm fund` for details #8 26.18 #8 26.18 found 0 vulnerabilities #8 26.18 npm notice #8 26.18 npm notice New minor version of npm available! 10.7.0 -> 10.8.0 #8 26.18 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.0 #8 26.18 npm notice To update run: npm install -g npm@10.8.0 #8 26.18 npm notice #8 DONE 36.3s
> 
> #9 [aipan-netdisk-search 5/6] RUN npm run build #9 0.416 #9 0.416 > nuxt-app@1.0.0 build #9 0.416 > nuxt build #9 0.416 #9 0.771 Nuxt 3.11.2 with Nitro 2.9.6 #9 0.783 #9 0.783 ERROR (node:17) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated. #9 0.783 (Use node --trace-deprecation ... to show where the warning was created) #9 0.783 #9 3.696 [nuxt:tailwindcss] ℹ Using default Tailwind CSS file #9 4.318 #9 4.318 ERROR (node:17) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension. #9 4.318 #9 6.085 ℹ Building client... #9 6.099 ℹ vite v5.2.11 building for production... #9 6.152 ℹ transforming... #9 6.877 #9 6.877 ERROR (node:17) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension. #9 6.877 #9 6.878 #9 6.878 ERROR (node:17) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension. #9 6.878 #9 17.34 ℹ ✓ 1631 modules transformed.
> 
> 大佬，看下过程有几个地方编译报错，全盘搜索错误，其它正常。

都是一些警告，而且本地测试没问题，盲猜全盘搜索不能用和地区有关系
